package com.example.fnotepro.util

enum class AppLanguage(val code: String, val label: String, val isRtl: Boolean) {
    ARABIC("ar", "🇸🇦 العربية", true),
    FRENCH("fr", "🇫🇷 Français", false),
    ENGLISH("en", "🇬🇧 English", false)
}

object Localization {
    const val APP_LOGO_URL = "https://i.ibb.co/20q8Hsd9/1778351155986-removebg-preview.png"

    private val strings = mapOf(
        "ar" to mapOf(
            "app_title" to "F-Note Pro Max",
            "app_subtitle" to "إدارة الوفود السياحية والدبلوماسية",
            "login_info" to "🔐 يتم إنشاء الحسابات عن طريق السيد فهمي (مدير النظام)",
            "email" to "البريد الإلكتروني",
            "password" to "كلمة المرور",
            "login_btn" to "تسجيل الدخول",
            "offline_btn" to "🔄 الوضع بدون إنترنت",
            "search_placeholder" to "🔍 بحث عن مرشد أو رقم الهاتف...",
            "add_guide_title" to "➕ إضافة مرشد جديد",
            "edit_guide_title" to "✏️ تعديل بيانات المرشد",
            "guide_name" to "اسم المرشد",
            "guide_name_opt" to "اسم المرشد (اختياري)",
            "phone" to "رقم الجوال",
            "nationality" to "الجنسية",
            "people_count" to "عدد الأفراد",
            "cars_count" to "عدد السيارات / الحافلات",
            "transport_type" to "نوع النقل",
            "delegation_type" to "نوع الوفد",
            "type_tourist" to "🌴 وفد سياحي",
            "type_diplomatic" to "🏛️ وفد دبلوماسي",
            "type_official" to "👔 وفد رسمي / حكومي",
            "type_business" to "💼 وفد أعمال",
            "type_sports" to "⚽ وفد رياضي",
            "small_bus" to "حافلة صغيرة",
            "large_bus" to "حافلة كبيرة",
            "car" to "سيارة",
            "van" to "فان",
            "motorcycle" to "🏍️ دراجة نارية",
            "other" to "أخرى",
            "from" to "من",
            "to" to "إلى",
            "plate" to "لوحة السيارة",
            "tunisian_plate" to "🇹🇳 لوحة تونسية قياسية",
            "foreign_plate" to "🌍 لوحة أجنبية / مخصصة",
            "plate_4_digits" to "الأرقام الأربعة (يسار)",
            "plate_tunis_label" to "تونس",
            "plate_3_digits" to "الأرقام الثلاثة (يمين)",
            "custom_plate" to "رقم اللوحة الأجنبية / الخاصة",
            "add_custom_plate" to "إضافة لوحة مخصصة أو أجنبية",
            "details" to "تفاصيل",
            "hide" to "إخفاء",
            "guide_photo" to "📸 صورة المرشد",
            "bus_photo" to "🚌 صور المركبات (حتى 5 صور)",
            "vehicle_photos_label" to "🚌 صور المركبات (حتى 5 صور)",
            "motorcycle_photos" to "🏍️ صور الدراجات النارية (حتى 10 صور)",
            "agency" to "الوكالة",
            "notes" to "ملاحظات وتفاصيل التنسيق",
            "visibility" to "مستوى الظهور",
            "public" to "🌍 عام (يظهر للجميع)",
            "private" to "🔒 خاص",
            "save_guide" to "💾 حفظ المرشد",
            "cancel" to "إلغاء",
            "delete" to "حذف",
            "edit" to "تعديل",
            "more" to "المزيد",
            "card" to "البطاقة",
            "follow_up" to "كرت المتابعة",
            "call" to "اتصال",
            "whatsapp" to "واتساب",
            "share_card" to "مشاركة البطاقة",
            "security_card_title" to "كرت التنسيق والمتابعة",
            "custom_group_label" to "🏷️ الفقرة المخصصة",
            "custom_group_placeholder" to "مثال: دخول المجموعة إلى hôtel les oliviers palace بأمان",
            "generate_card" to "🔄 إنشاء وتجهيز البطاقة",
            "card_ready" to "✅ البطاقة جاهزة للإرسال",
            "saved_numbers_label" to "📋 الأرقام المحفوظة (اضغط للإرسال)",
            "add_numbers_label" to "➕ إضافة أرقام جديدة (رقم في كل سطر)",
            "save_numbers" to "💾 حفظ الأرقام",
            "send_history" to "📜 سجل الإرسال",
            "resend" to "إعادة الإرسال",
            "safety_officer" to "عون السلامة",
            "safety_officer_section" to "معلومات عون السلامة (تضاف تلقائياً للوفود)",
            "safety_name" to "اسم عون السلامة",
            "safety_phone" to "هاتف عون السلامة",
            "profile_title" to "👤 تعديل الملف الشخصي",
            "display_name" to "اسم العرض",
            "save_profile" to "💾 حفظ التغييرات",
            "tools_section" to "أدوات متقدمة",
            "sync" to "مزامنة السحابة",
            "export_json" to "تصدير JSON",
            "export_pdf" to "تصدير تقرير الوفود",
            "logout" to "تسجيل الخروج",
            "language" to "اللغة",
            "terms" to "📜 شروط الخدمة والحقوق",
            "terms_text" to "تطبيق F-Note Pro Max مخصص لإدارة وتأمين الوفود السياحية والدبلوماسية ونزل Les Oliviers Palace بصفاقس. جميع الحقوق محفوظة للمطور السيد فهمي.",
            "developer_section" to "👨‍💻 قسم المطور",
            "manage_admins" to "🛡️ إدارة المديرين",
            "manage_users" to "👥 إدارة الحسابات",
            "view_all_guides" to "📋 جميع الإضافات (عامة وخاصة)",
            "created_at" to "تاريخ الإضافة:",
            "sent_at" to "تاريخ الإرسال:",
            "created_by" to "المنشئ:",
            "delete_confirm" to "هل أنت متأكد من حذف هذا المرشد؟",
            "saved_success" to "✅ تم الحفظ بنجاح",
            "deleted_success" to "🗑️ تم الحذف بنجاح",
            "weather_sfax" to "طقس صفاقس: 26°C مشمس معتدل",
            "map" to "الخريطة",
            "route_map" to "🗺️ خريطة ومسار الوفد",
            "open_google_maps" to "🗺️ فتح المسار في Google Maps",
            "approximate_route" to "المسار التقريبي",
            "origin_location" to "نقطة الانطلاق (من)",
            "destination_location" to "الوجهة (إلى)",
            "view_route_details" to "عرض المسار على الخريطة",
            "no_guides" to "😕 لا يوجد مرشدين مضافين حالياً"
        ),
        "fr" to mapOf(
            "app_title" to "F-Note Pro Max",
            "app_subtitle" to "Gestion des délégations touristiques et diplomatiques",
            "login_info" to "🔐 Les comptes sont créés par M. Fahmi (Administrateur)",
            "email" to "E-mail",
            "password" to "Mot de passe",
            "login_btn" to "Connexion",
            "offline_btn" to "🔄 Mode Hors Ligne",
            "search_placeholder" to "🔍 Rechercher guide ou téléphone...",
            "add_guide_title" to "➕ Ajouter un guide",
            "edit_guide_title" to "✏️ Modifier le guide",
            "guide_name" to "Nom du guide",
            "guide_name_opt" to "Nom du guide (optionnel)",
            "phone" to "Téléphone",
            "nationality" to "Nationalité",
            "people_count" to "Nombre de personnes",
            "cars_count" to "Nombre de véhicules",
            "transport_type" to "Type de transport",
            "delegation_type" to "Type de délégation",
            "type_tourist" to "🌴 Touristique",
            "type_diplomatic" to "🏛️ Diplomatique",
            "type_official" to "👔 Officiel",
            "type_business" to "💼 Affaires",
            "type_sports" to "⚽ Sportif",
            "small_bus" to "Petit bus",
            "large_bus" to "Grand bus",
            "car" to "Voiture",
            "van" to "Van",
            "motorcycle" to "🏍️ Moto",
            "other" to "Autre",
            "from" to "De",
            "to" to "À",
            "plate" to "Plaque d'immatriculation",
            "tunisian_plate" to "🇹🇳 Plaque tunisienne standard",
            "foreign_plate" to "🌍 Plaque étrangère / spéciale",
            "plate_4_digits" to "4 chiffres (gauche)",
            "plate_tunis_label" to "تونس",
            "plate_3_digits" to "3 chiffres (droite)",
            "custom_plate" to "Numéro de plaque étrangère / spéciale",
            "add_custom_plate" to "Ajouter plaque personnalisée",
            "details" to "Détails",
            "hide" to "Masquer",
            "guide_photo" to "📸 Photo du guide",
            "bus_photo" to "🚌 Photos véhicules (max 5)",
            "vehicle_photos_label" to "🚌 Photos véhicules (max 5)",
            "motorcycle_photos" to "🏍️ Photos moto (max 10)",
            "agency" to "Agence",
            "notes" to "Notes et détails",
            "visibility" to "Visibilité",
            "public" to "🌍 Public",
            "private" to "🔒 Privé",
            "save_guide" to "💾 Enregistrer le guide",
            "cancel" to "Annuler",
            "delete" to "Supprimer",
            "edit" to "Modifier",
            "more" to "Plus",
            "card" to "Carte",
            "follow_up" to "Fiche Suivi",
            "call" to "Appeler",
            "whatsapp" to "WhatsApp",
            "share_card" to "Partager la carte",
            "security_card_title" to "Fiche de Coordination & Suivi",
            "custom_group_label" to "🏷️ Paragraphe personnalisé",
            "custom_group_placeholder" to "Ex: Entrée du groupe à l'hôtel Les Oliviers Palace en sécurité",
            "generate_card" to "🔄 Générer la carte",
            "card_ready" to "✅ Carte prête à l'envoi",
            "saved_numbers_label" to "📋 Numéros enregistrés (cliquer pour envoyer)",
            "add_numbers_label" to "➕ Ajouter des numéros (un par ligne)",
            "save_numbers" to "💾 Enregistrer les numéros",
            "send_history" to "📜 Historique d'envoi",
            "resend" to "Renvoyer",
            "safety_officer" to "Agent de sécurité",
            "safety_officer_section" to "Agent de sécurité (attaché automatiquement)",
            "safety_name" to "Nom de l'agent",
            "safety_phone" to "Téléphone de l'agent",
            "profile_title" to "👤 Modifier le profil",
            "display_name" to "Nom d'affichage",
            "save_profile" to "💾 Enregistrer",
            "tools_section" to "Outils avancés",
            "sync" to "Synchronisation",
            "export_json" to "Exporter JSON",
            "export_pdf" to "Exporter Rapport",
            "logout" to "Déconnexion",
            "language" to "Langue",
            "terms" to "📜 Conditions d'utilisation",
            "terms_text" to "Application F-Note Pro Max pour la gestion et sécurisation des délégations à l'hôtel Les Oliviers Palace. Tous droits réservés à M. Fahmi.",
            "developer_section" to "👨‍💻 Section Développeur",
            "manage_admins" to "🛡️ Gérer les admins",
            "manage_users" to "👥 Gérer les comptes",
            "view_all_guides" to "📋 Tous les ajouts",
            "created_at" to "Créé le :",
            "sent_at" to "Envoyé le :",
            "created_by" to "Créateur :",
            "delete_confirm" to "Voulez-vous vraiment supprimer ce guide ?",
            "saved_success" to "✅ Enregistré avec succès",
            "deleted_success" to "🗑️ Supprimé avec succès",
            "weather_sfax" to "Météo Sfax: 26°C Ensoleillé",
            "map" to "Carte",
            "route_map" to "🗺️ Carte de l'itinéraire",
            "open_google_maps" to "🗺️ Ouvrir dans Google Maps",
            "approximate_route" to "Itinéraire approximatif",
            "origin_location" to "Point de départ (De)",
            "destination_location" to "Destination (À)",
            "view_route_details" to "Voir sur la carte",
            "no_guides" to "😕 Aucun guide enregistré"
        ),
        "en" to mapOf(
            "app_title" to "F-Note Pro Max",
            "app_subtitle" to "Touristic & Diplomatic Delegations Management",
            "login_info" to "🔐 Accounts are provisioned by Mr. Fahmi (System Administrator)",
            "email" to "Email Address",
            "password" to "Password",
            "login_btn" to "Sign In",
            "offline_btn" to "🔄 Offline Mode",
            "search_placeholder" to "🔍 Search guide or phone...",
            "add_guide_title" to "➕ Add New Guide",
            "edit_guide_title" to "✏️ Edit Guide Details",
            "guide_name" to "Guide Name",
            "guide_name_opt" to "Guide Name (optional)",
            "phone" to "Phone Number",
            "nationality" to "Nationality",
            "people_count" to "Number of People",
            "cars_count" to "Number of Cars / Buses",
            "transport_type" to "Transport Type",
            "delegation_type" to "Delegation Type",
            "type_tourist" to "🌴 Tourist Delegation",
            "type_diplomatic" to "🏛️ Diplomatic Delegation",
            "type_official" to "👔 Official Delegation",
            "type_business" to "💼 Business Delegation",
            "type_sports" to "⚽ Sports Delegation",
            "small_bus" to "Small Bus",
            "large_bus" to "Large Bus",
            "car" to "Car",
            "van" to "Van",
            "motorcycle" to "🏍️ Motorcycle",
            "other" to "Other",
            "from" to "From",
            "to" to "To",
            "plate" to "Vehicle Plate",
            "tunisian_plate" to "🇹🇳 Standard Tunisian Plate",
            "foreign_plate" to "🌍 Foreign / Custom Plate",
            "plate_4_digits" to "4 Digits (Left)",
            "plate_tunis_label" to "تونس",
            "plate_3_digits" to "3 Digits (Right)",
            "custom_plate" to "Foreign / Custom Plate Number",
            "add_custom_plate" to "Add Custom or Foreign Plate",
            "details" to "Details",
            "hide" to "Hide",
            "guide_photo" to "📸 Guide Photo",
            "bus_photo" to "🚌 Vehicle Photos (up to 5)",
            "vehicle_photos_label" to "🚌 Vehicle Photos (up to 5)",
            "motorcycle_photos" to "🏍️ Motorcycle Photos (up to 10)",
            "agency" to "Travel Agency",
            "notes" to "Coordination Notes",
            "visibility" to "Visibility",
            "public" to "🌍 Public (Visible to all)",
            "private" to "🔒 Private",
            "save_guide" to "💾 Save Guide",
            "cancel" to "Cancel",
            "delete" to "Delete",
            "edit" to "Edit",
            "more" to "More",
            "card" to "Card",
            "follow_up" to "Follow-up Card",
            "call" to "Call",
            "whatsapp" to "WhatsApp",
            "share_card" to "Share Card",
            "security_card_title" to "Coordination & Follow-up Card",
            "custom_group_label" to "🏷️ Custom Paragraph",
            "custom_group_placeholder" to "E.g. Safe entrance of group into Les Oliviers Palace Hotel",
            "generate_card" to "🔄 Generate Card",
            "card_ready" to "✅ Card Ready to Dispatch",
            "saved_numbers_label" to "📋 Saved Phone Numbers (Click to send)",
            "add_numbers_label" to "➕ Add New Numbers (one per line)",
            "save_numbers" to "💾 Save Numbers",
            "send_history" to "📜 Send History",
            "resend" to "Resend",
            "safety_officer" to "Safety Officer",
            "safety_officer_section" to "Safety Officer Info (auto attached)",
            "safety_name" to "Officer Name",
            "safety_phone" to "Officer Phone",
            "profile_title" to "👤 Edit User Profile",
            "display_name" to "Display Name",
            "save_profile" to "💾 Save Profile",
            "tools_section" to "Advanced Tools",
            "sync" to "Cloud Sync",
            "export_json" to "Export JSON",
            "export_pdf" to "Export Report",
            "logout" to "Sign Out",
            "language" to "Language",
            "terms" to "📜 Terms & Service Rights",
            "terms_text" to "F-Note Pro Max is designed for delegation logistics and security management at Les Oliviers Palace Hotel, Sfax. All rights reserved to Mr. Fahmi.",
            "developer_section" to "👨‍💻 Developer Section",
            "manage_admins" to "🛡️ Manage Admins",
            "manage_users" to "👥 Manage Accounts",
            "view_all_guides" to "📋 All Guides (Public & Private)",
            "created_at" to "Created at:",
            "sent_at" to "Sent at:",
            "created_by" to "Created by:",
            "delete_confirm" to "Are you sure you want to delete this guide?",
            "saved_success" to "✅ Saved successfully",
            "deleted_success" to "🗑️ Deleted successfully",
            "weather_sfax" to "Sfax Weather: 26°C Sunny",
            "map" to "Map",
            "route_map" to "🗺️ Delegation Route Map",
            "open_google_maps" to "🗺️ Open Route in Google Maps",
            "approximate_route" to "Approximate Route",
            "origin_location" to "Departure (From)",
            "destination_location" to "Destination (To)",
            "view_route_details" to "View Route on Map",
            "no_guides" to "😕 No guides recorded yet"
        )
    )

    fun get(key: String, lang: AppLanguage): String {
        return strings[lang.code]?.get(key)
            ?: strings["ar"]?.get(key)
            ?: key
    }
}
